import Link from 'next/link';
import {ArrowUpRight,ArrowRight} from 'lucide-react';
import {Article,BLUE_SERIES,minutes,dateLabel} from '@/lib/content';
export function Logo({color='red'}:{color?:string}){return <span className="brand-logo"><img src={'/brand/'+color+'.png'} alt="revista NOEMA" width="2048" height="2048"/></span>}
export function Header({blue=false}:{blue?:boolean}){return <header className={'site-header '+(blue?'blue-header':'')}><Link href="/" aria-label="Revista NOEMA — início"><Logo color={blue?'white':'red'}/></Link><nav aria-label="Navegação principal"><Link href="/">Artigos</Link><Link href="/filosofia-da-inteligencia">Filosofia da Inteligência</Link><Link href="/contato">Contato <ArrowUpRight size={15}/></Link></nav><span className="header-note">TECNOLOGIA SOB PERSPECTIVA</span></header>}
export function Footer(){return <footer className="site-footer"><div className="footer-top"><Logo color="white"/><p>Inteligência artificial.<br/>Pensamento independente.</p><Link href="/contato">Converse com a revista <ArrowUpRight size={22}/></Link></div><div className="footer-bottom"><span>© {new Date().getFullYear()} NOEMA</span><span>IA · CULTURA · PODER · FILOSOFIA</span><Link href="/admin">Área editorial</Link></div></footer>}
export function Art({cover,className=''}:{cover:string,className?:string}){return <div className={'article-art art-'+cover+' '+className} aria-hidden="true"><img src={'/art/'+cover+'.png'} alt="" width="1122" height="1402" loading="lazy"/></div>}
export function Meta({article}:{article:Article}){return <div className="article-meta"><span>{article.category}</span><span>{minutes(article.body)} min de leitura</span></div>}
export function ArticleCard({article}:{article:Article}){return <Link className={'article-card '+(article.series===BLUE_SERIES?'philosophy-card':'')} href={'/artigos/'+article.slug}><Art cover={article.cover}/><Meta article={article}/><h3>{article.title}</h3><p>{article.excerpt}</p><div className="card-bottom"><time dateTime={article.published_at}>{dateLabel(article.published_at)}</time><ArrowUpRight size={22}/></div></Link>}
export function Body({body}:{body:string}){return <div className="article-body">{body.split(/\n\s*\n/).filter(Boolean).map((p,i)=>p.startsWith('## ')?<h2 key={i}>{p.slice(3)}</h2>:p.startsWith('> ')?<blockquote key={i}>{p.slice(2)}</blockquote>:<p key={i}>{p}</p>)}</div>}
export function SeriesBanner(){return <Link href="/filosofia-da-inteligencia" className="series-banner"><div><span className="eyebrow">UMA SÉRIE DA NOEMA</span><h2>Filosofia da<br/><em>Inteligência.</em></h2><p>Mente, desejo, consciência.<br/>As perguntas que não cabem em um benchmark.</p><span className="text-link">Explorar a série <ArrowRight size={19}/></span></div><Art cover="desejo"/></Link>}
