import Link from 'next/link';
import {notFound} from 'next/navigation';
import {ArrowLeft} from 'lucide-react';
import {Header,Footer,Art,Body} from '@/components/magazine';
import {getArticle} from '@/lib/db';
import {BLUE_SERIES,dateLabel,minutes} from '@/lib/content';
export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;try{const a=await getArticle(slug);return {title:a?.title||'Artigo não encontrado',description:a?.excerpt};}catch{return {title:'Artigo indisponível'}}}
export default async function ArticlePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;let article;try{article=await getArticle(slug)}catch{return <><Header/><main className="empty-page"><h1>Artigo temporariamente indisponível.</h1><p>Tente novamente em instantes.</p></main><Footer/></>};if(!article)notFound();const blue=article.series===BLUE_SERIES;return <><Header blue={blue}/><main className={'reading-page '+(blue?'blue-reading':'')}><section className="reading-heading"><Link className="back-link" href={blue?'/filosofia-da-inteligencia':'/#artigos'}><ArrowLeft size={16}/> {blue?'Filosofia da Inteligência':'Todos os artigos'}</Link><span className="eyebrow">{article.category}</span><h1>{article.title}</h1><p className="reading-excerpt">{article.excerpt}</p><div className="reading-meta"><span>REDAÇÃO NOEMA</span><time>{dateLabel(article.published_at)}</time><span>{minutes(article.body)} min de leitura</span></div></section><Art cover={article.cover} className="reading-art"/><Body body={article.body}/>{article.sources&&<section className="sources"><h2>Fontes e leituras</h2>{article.sources.split('\n').filter(Boolean).map((line,i)=>{const [label,raw]=line.split('|');const url=raw?.trim();return url&&/^https?:\/\//.test(url)?<a key={i} href={url} target="_blank" rel="noopener noreferrer">{label.trim()} ↗</a>:<p key={i}>{label}</p>})}</section>}<div className="reading-end"><span>Continue pensando.</span><Link href={blue?'/filosofia-da-inteligencia':'/#artigos'}>Mais artigos da NOEMA ↗</Link></div></main><Footer/></>}
